PizzaShop/Controllers/AccountManagerOrderAppController.cs
using System.Diagnostics;
using System.Security.Claims;
using DAL.Interfaces;
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Entities.ViewModel;
using X.PagedList.Extensions;
using BLL.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text.Json.Nodes;
using System.Linq;
using DocumentFormat.OpenXml.Office.CustomUI;

namespace PizzaShop.Controllers;


public class AccountManagerOrderAppController : Controller
{
    // private readonly ILogger<HomeController> _logger;

    private readonly IAccountManagerOrderAppService _accountmanagerorderapp;
    private readonly IMenuService _menuService;
    private readonly IOrderService _orderService;

    private readonly ITaxService _taxService;
    private readonly ITableAndSectionService _tableandsectionService;


    public AccountManagerOrderAppController(IAccountManagerOrderAppService accountmanagerorderapp, ITableAndSectionService tableandsectionService, IMenuService menuService, IOrderService orderService, ITaxService taxService)
    {
        _menuService = menuService;
        _accountmanagerorderapp = accountmanagerorderapp;
        _tableandsectionService = tableandsectionService;
        _orderService = orderService;
        _taxService = taxService;
    }

    [Authorize(Policy = "AccountManagerPolicy")]
    public IActionResult Table()
    {
        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        var section = _accountmanagerorderapp.GetOrderSection();
        return View(section);
    }

    [Authorize(Policy = "AccountManagerPolicy")]
    public IActionResult GetWaitingList(int sectionId)
    {
        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        Console.WriteLine("Hi i am in Water");
        var waitinglist = _accountmanagerorderapp.GetAllWaitingListCustomer(sectionId);
        return PartialView("_WaitingList", waitinglist);
    }

    [Authorize(Policy = "AccountManagerPolicy")]
    public IActionResult GetWaitingData(int waitingId)
    {

        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        var waitingData = _accountmanagerorderapp.GetWaitingData(waitingId);
        return PartialView("_CustomerDetailsForm", waitingData);
    }

    public IActionResult GetWaitingDataByEmail(string email)
    {

        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        var waitingData = _accountmanagerorderapp.GetWaitingDataByEmail(email);
        return PartialView("_CustomerDetailsForm", waitingData);
    }

    public IActionResult AddCustomerDetail([FromBody] JsonObject customerdata)
    {
        bool success = _accountmanagerorderapp.AddOrUpdateCustomer(customerdata);
        string email = (string)customerdata["email"];
        var customerId = _accountmanagerorderapp.GetCustomerIDByName(email);
        if (success)
        {
            return Json(new { success = true, message = "Customer Added Successfully!", customerId = customerId });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }

    public IActionResult GetWaitingToken(string email)
    {
        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        var waitingData = _accountmanagerorderapp.GetWaitingDataByEmail(email);
        return PartialView("_WaitingTokenDetailsPV", waitingData);
    }

    public IActionResult AddInWaitingList([FromBody] JsonObject customerdata)
    {
        bool success = _accountmanagerorderapp.AddInWaitingList(customerdata);

        if (success)
        {
            return Json(new { success = true, message = "Customer Added Successfully!" });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }
    [Authorize(Policy = "ChefOrAccountManagerPolicy")]
    public IActionResult KOT()
    {
        var categories = _menuService.GetAllCategories();
        var categoryvm = new MenuCategoryVM
        {
            CategoryName = categories.FirstOrDefault().CategoryName,
            menuCategories = categories
        };
        return View(categoryvm);
    }

    public IActionResult GetKOT(int categoryId, string? status)
    {
        List<OrderVM> category = _accountmanagerorderapp.GetOrderCategoryItem(categoryId, status);
        return PartialView("_KOTCard", category);
    }

    public IActionResult GetOrderDetails([FromBody] List<OrderVM> orderDetailsArray)
    {
        return PartialView("_KOTPrepare", orderDetailsArray);
    }

    public IActionResult MakePrepare([FromBody] List<PrepareItemVM> prepare)
    {
        bool success = _accountmanagerorderapp.UpdateOrderStatus(prepare);

        if (success)
        {
            return Json(new { success = true, message = "Order Status Updated Successfully!" });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }

    [Authorize(Policy = "AccountManagerPolicy")]
    public IActionResult WaitingList()
    {
        var sections = _tableandsectionService.GetAllSection();
        var sectionvm = sections.Select(Section => new SectionVM
        {
            SectionId = Section.SectionId,
            SectionName = Section.SectionName,
            WaitingList = _accountmanagerorderapp.GetAllWaitingListCustomer(Section.SectionId).Count()
        }).ToList();
        return View(sectionvm);
    }

    public IActionResult GetWaitingListBySectionId(int sectionId)
    {
        var sections = _tableandsectionService.GetAllSection();
        ViewBag.Sections = sections.Select(r => new SelectListItem
        {
            Value = r.SectionId.ToString(),
            Text = r.SectionName
        }).ToList();
        // var tables = _tableandsectionService.Get
        var waitingData = _accountmanagerorderapp.GetAllWaitingListCustomer(sectionId);
        return PartialView("_WaitingListPV", waitingData);
    }

    // public IActionResult GetTableBySectionId(int sectionId)
    // {
    //     var tables = _tableandsectionService.GetAvailableTablesBySectionId(sectionId);
    // }

    public JsonResult GetTableListBySection(int sectionId)
    {
        var tables = _tableandsectionService.GetAvailableTablesBySectionId(sectionId);
        return Json(tables);

    }

    [Authorize(Policy = "AccountManagerPolicy")]
    public IActionResult MenuOrderApp(int customerId)
    {
        var categories = _menuService.GetAllCategories();
        ViewBag.CustomerId = customerId;
        var tables = _accountmanagerorderapp.GetTablesByCustomerId(customerId);
        var tax = _taxService.GetAllTaxes();


        var categoryvm = new MenuCategoryVM
        {
            CategoryName = categories.FirstOrDefault()?.CategoryName,
            customerTables = tables,
            menuCategories = categories,
            Taxes = tax
        };

        return View(categoryvm);
    }

    public IActionResult GetItemByCategory(int CategoryId)
    {
        var items = _menuService.GetItemByCategoryId(CategoryId);
        return PartialView("_MenuItemCard", items);
    }

    public IActionResult AddToFavouriteItem(int ItemId)
    {
        bool success = _accountmanagerorderapp.AddToFavouriteItem(ItemId);

        if (success)
        {
            return Json(new { success = true, message = "Item Added to Favourites!" });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }
    public IActionResult GetFavouriteItem()
    {
        var favouriteItems = _accountmanagerorderapp.GetFavouriteItem();
        return PartialView("_MenuItemCard", favouriteItems);
    }

    public IActionResult DeleteWaitingToken(int waitingId)
    {
        bool success = _accountmanagerorderapp.DeleteWaitingToken(waitingId);

        if (success)
        {
            return Json(new { success = true, message = "Waiting Token Deleted Successfully!" });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }

    public IActionResult AssignTable(int waitingId, int tableId)
    {
        bool success = _accountmanagerorderapp.AssignTable(waitingId, tableId);
        // var customer = _accountmanagerorderapp.  
        if (success)
        {
            return Json(new { success = true, message = "Table Assigned Successfully!" });
        }
        else
        {
            return Json(new { success = false, message = "An error occurred while processing the request." });
        }
    }

    public IActionResult GetModifierFromItem(int ItemId)
    {
        var combinedModifier = _accountmanagerorderapp.GetItemModifier(ItemId);
        return PartialView("_MenuModifierPV", combinedModifier);
    }

    public IActionResult GetMenuItemDetails([FromBody] List<MenuCategoryVM> ItemDetailsArray)
    {

PizzaShop/Views/AccountManagerOrderApp/KOT.cshtml
@model Entities.ViewModel.MenuCategoryVM

@{
    Layout = "_LayoutOrder";
    ViewData["Title"] = "Table View";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizza Shop</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <style>
        .prev-btn, .next-btn {
            display: block !important
        }
    </style>
</head>

<body style="background-color: rgb(245,245,245);">
    <div style="padding-top: 100px; padding-left: 50px; padding-right: 50px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="fs-2 fw-bold webybtn mb-3">KOT</div>
                </div>
            </div>
        </div>

        <!-- Bootstrap Tabs -->
        <ul class="nav nav-tabss border-0 bg-white p-3 pt-2 pb-0 rounded-3" id="categoryTabs">
            <li class="nav-item">
                <a class="nav-link active text-nav-color border-bottom border-primary fs-5 fw-bold" data-category="0"
                    aria-selected="true" onclick="showCategory(0, 'All')">
                    All
                </a>
            </li>
            @foreach (var category in Model.menuCategories)
            {
                <li class="nav-item">
                    <a class="nav-link categoryBtn text-nav-color fs-5 fw-bold" data-category="@category.CategoryId"
                        onclick="showCategory(@category.CategoryId, '@category.CategoryName')">
                        @category.CategoryName
                    </a>
                </li>
            }
        </ul>

        <!-- Tab Content -->
        <div class="tab-content mt-3 bg-white" id="categoryTabContent">
            <div class="d-flex align-items-center justify-content-between p-3">

                <input type="hidden" id="selectedCategoryId" value="0" />
                <div id="categoryName">
                </div>
                <div class="fs-3 fw-bold webybtn mb-3">
                    <div class="d-flex align-items-center gap-2">
                        <button type="button" class="btn text-center progressbtn"
                            onclick="handleStatus('In Progress')"
                            style="background-color: rgba(0, 102, 167, 1); border-color: rgba(0, 102, 167, 1); color: white;">
                            In Progress
                        </button>

                        <button type="button" class="btn readybtn" onclick="handleStatus('Ready')"
                            style="background-color: white; border-color: rgba(0, 102, 167, 1); color: rgba(0, 102, 167, 1);">
                            Ready
                        </button>

                        <button class="btn  pagination-btn prev-btn"
                            style="background-color: white; border-color: rgba(0, 102, 167, 1); color: rgba(0, 102, 167, 1);">
                            <i class="fa-solid fa-chevron-left"></i>
                        </button>
                        <button class="btn  pagination-btn next-btn"
                            style="background-color: white; border-color: rgba(0, 102, 167, 1); color: rgba(0, 102, 167, 1);overflow: visible !important;">
                            <i class="fa-solid fa-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Placeholder for Partial View -->
            <div class="category-content" id="kotcard">

            </div>

        </div>
    </div>



</body>

<script>
    $(document).ready(function () {
        // Show the initial category content
        showCategory(0, 'All');
        $(".card-container").click(function () {
            $("#kotmodal").modal("show");
        });
    }); 
    function showCategory(categoryId, categoryName) {
        // Hide all category contents

        $('#selectedCategoryId').val(categoryId);

        $('#categoryName').html(`<span class="fs-3 fw-bold webybtn">${categoryName}</span>`);

        $(".category-content").hide();
        var status = "In Progress";
        console.log(categoryId);
        console.log(status);


        $.ajax({
            url: '@Url.Action("GetKOT", "AccountManagerOrderApp")',
            type: 'GET',
            data: { categoryId: categoryId, status: status },
            success: function (data) {
                $('#kotcard').html(data);
                $('#kotcard').find('.category-content').show();  // Ensure newly added content is visible
                $('#kotcard').show();

            },
            error: function (xhr, status, error) {
                console.error("Error fetching category items:", error);
            }
        });

        $(".nav-link").removeClass("text-primary border-bottom border-primary fw-bold").addClass("text-nav-color");

        // Add active style to selected
        $(`[data-category="${categoryId}"]`)
            .removeClass("text-nav-color")
            .addClass("text-primary border-bottom border-primary fw-bold");
    }
    $(".readybtn").click(function () {
        $(this).css({
            "background-color": "rgba(0, 102, 167, 1)",
            "border-color": "rgba(0, 102, 167, 1)",
            "color": "white"
        });
        $(".progressbtn").css({
            "background-color": "white",
            "border-color": "rgba(0, 102, 167, 1)",
            "color": "rgba(0, 102, 167, 1)"
        });
    });
    $(".progressbtn").click(function () {
        $(this).css({
            "background-color": "rgba(0, 102, 167, 1)",
            "border-color": "rgba(0, 102, 167, 1)",
            "color": "white"
        });
        $(".readybtn").css({
            "background-color": "white",
            "border-color": "rgba(0, 102, 167, 1)",
            "color": "rgba(0, 102, 167, 1)"
        });
    });
    function handleStatus(status) {
        var categoryId = $('#selectedCategoryId').val();
        console.log("Selected CategoryId:", categoryId, "Status:", status);
        window.myselectedstatus = status;

        $.ajax({
            url: '@Url.Action("GetKOT", "AccountManagerOrderApp")',
            type: 'GET',
            data: { categoryId: categoryId, status: status },
            success: function (data) {
                @* console.log("Category items fetched successfully:", data); *@
                $('#kotcard').html(data);
                $('#kotcard').find('.category-content').show();  // Ensure newly added content is visible
                $('#kotcard').show();
            },
            error: function (xhr, status, error) {
                $('#kotcard').empty();
                
                console.log("IN Error Page");
                @* console.error("Error fetching category items:", error); *@
            }
        });

    }
</script>

</html>

PizzaShop/Views/AccountManagerOrderApp/WaitingList.cshtml
@model List<Entities.ViewModel.SectionVM>

@{
    Layout = "_LayoutOrder";
    ViewData["Title"] = "Table View";

    var totalwaitingList = Model.Sum(x => x.WaitingList);
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizza Shop</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
</head>

<body style="background-color: rgb(245,245,245);">
    <div style="padding-top: 100px; padding-left: 50px; padding-right: 50px;">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <div class="fs-2 fw-bold webybtn mb-3">Waiting List</div>
                </div>
            </div>
        </div>

        <!-- Bootstrap Tabs -->
        <ul class="nav nav-tabss border-0 bg-white p-3 pt-2 pb-0 rounded-3" id="categoryTabs">
            <li class="nav-item">
                <a class="nav-link active text-nav-color border-bottom border-primary fs-5 fw-bold" data-category="0"
                    aria-selected="true" onclick="showWaitinList(0)">
                    All (@totalwaitingList)
                </a>
            </li>
            @foreach (var sections in Model)
            {
                <li class="nav-item">
                    <a class="nav-link categoryBtn text-nav-color fs-5 fw-bold" data-category="@sections.SectionId"
                        aria-selected="false" onclick="showWaitinList(@sections.SectionId)">@sections.SectionName
                        (@sections.WaitingList)
                    </a>
                </li>
            }
        </ul>

        <!-- Placeholder for Partial View -->
        <div class="category-content bg-white" id="kotcard">

        </div>


    </div>



</body>

<script>
    let sectionId = 0;
    let waitingId = 0;
    let tableId = 0;
    $(document).ready(function () {
        // Show the initial category content
        showWaitinList(0);
        $(".card-container").click(function () {
            $("#kotmodal").modal("show");
        });



        $(document).on('click', '.deletebtn', function (e) {
            e.preventDefault();
            var waitingListId = $(this).data("id");
            waitingId = waitingListId;
            console.log(waitingListId);
            $("#waitingtokendetaildeletemodal").modal("show");
            $(".deletewaitingtokenbtn").click(function () {
                $.ajax({
                    url: '@Url.Action("DeleteWaitingToken", "AccountManagerOrderApp")',
                    type: 'POST',
                    data: { waitingId: waitingListId },
                    success: function (response) {
                        $("#waitingtokendetaildeletemodal").modal("hide");
                        toastr.success('Waiting Token Deleted Successfully!', "Success");
                        showWaitinList(sectionId);
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', xhr.responseText); // Log detailed error
                    }
                });
            });
        });
        $(document).on('change', '#tableDropdown', function (e) {
            e.preventDefault();
            var selectedTableId = $(this).val();
            console.log(selectedTableId);
            tableId = selectedTableId;
        });
        $(document).on('click', '.assigntablebtn', function (e) {
            e.preventDefault();
            waitingId = $(this).data("id");
            console.log(waitingId);
            $("#assignwaitingtokendetailmodal").modal("show");
            $(document).on('click','.assigntablefinalbtn',function (e) {
                e.preventDefault();
                $.ajax({
                    url: '@Url.Action("AssignTable", "AccountManagerOrderApp")',
                    type: 'POST',
                    data: { waitingId: waitingId, tableId: tableId },
                    success: function (response) {
                        $("#assignwaitingtokendetailmodal").modal("hide");
                        toastr.success('Table Assigned Successfully!', "Success");
                        showWaitinList(sectionId);
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', xhr.responseText); // Log detailed error
                    }
                });
            });
        });
    });
    function showWaitinList(SectionId) {

        $('#selectedCategoryId').val(SectionId);

        sectionId = SectionId;
        $(".category-content").hide();
        console.log(SectionId);


        $.ajax({
            url: '@Url.Action("GetWaitingListBySectionId", "AccountManagerOrderApp")',
            type: 'GET',
            data: { sectionId: SectionId },
            success: function (data) {
                $('#kotcard').html(data);

                $('#kotcard').find('.category-content').show();  // Ensure newly added content is visible
                $('#kotcard').show();

            },
            error: function (xhr, status, error) {
                console.error("Error fetching category items:", error);
            }
        });

        $(".nav-link").removeClass("text-primary border-bottom border-primary fw-bold").addClass("text-nav-color");

        // Add active style to selected
        $(`[data-category="${SectionId}"]`)
            .removeClass("text-nav-color")
            .addClass("text-primary border-bottom border-primary fw-bold");
    }


</script>

</html>

PizzaShop/Views/AccountManagerOrderApp/_KOTPrepare.cshtml
@model List<Entities.ViewModel.OrderVM>

<div>
    <div class="d-flex justify-content-between">

        <span class="fs-5 fw-bold OrderId" data-orderid="@Model.FirstOrDefault().OrderId">OrderId ID: #@Model.FirstOrDefault().OrderId</span>
    </div>
</div>
<div
    class="d-flex justify-content-between pb-2 text-secondary border border-bottom border-top-0 border-start-0 border-end-0">
    <span>
        Item
    </span>
    <span>
        Quantity
    </span>
</div>
@foreach (var item in Model.FirstOrDefault().OrderItems)
{
    <span class="d-flex justify-content-between text-secondary ps-3 pt-2">
        <span><input class="form-check-input" type="checkbox" value="@item.ItemId" id="@item.ItemId">@item.ItemName
            <ul>
                <li>
                    @if (item.Modifiers != null && item.Modifiers.Any())
                    {
                        foreach (var modifier in item.Modifiers)
                        {
                            <span class="d-flex justify-content-between text-secondary">
                                <span>@modifier.ModifierName</span>
                            </span>
                        }
                    }
                </li>
            </ul>
        </span>
        <span class="input-group border border-primary" style="width: 120px; height: 40px;" >
            <button class="btn  btn-minus" type="button">-</button>
            <input type="text" class="form-control bg-white text-center qty-input" value="@item.Quantity" readonly>
            <button class="btn  btn-plus" type="button">+</button>
        </span>
    </span>

}

<script>
    @* let maxQty;  *@
    @* maxQty = 0;  *@
    var status = '@Model.FirstOrDefault().OrderItems.FirstOrDefault().Status';
    $(document).ready(function () {
        $('.prepareitem').submit(function (e) {
            e.preventDefault();

            var prepare = [];

            let orderId = $(".OrderId").data("orderid");   // orderId from form attribute
            let items = $(this).find('.form-check-input:checked');

            if (items.length == 0) {
                alert('Please select at least one item.');
                return;
            }

            items.each(function (index) {
                let itemId = $(this).val();
                let quantity = $(this).closest('.d-flex').find('.qty-input').val();

                prepare.push({
                    orderId: orderId,
                    itemId: itemId,
                    quantity: quantity,
                    status: status
                });
            });

            console.log(prepare);

            $.ajax({
                type: "POST",
                url: '/AccountManagerOrderApp/MakePrepare',
                data: JSON.stringify(prepare),
                contentType: "application/json",
                success: function (response) {
                    alert(response.message);
                }
            });
        });
        $('.btn-plus').click(function () {
            let input = $(this).siblings('.qty-input');
            let current = parseInt(input.val());
            console.log(current);
            @* console.log(maxQty); *@

            if (current < 0) {
                input.val(current + 1);
                @* if (maxQty == 0) {
                    maxQty = current;
                } *@
            }
        });

        $('.btn-minus').click(function () {
            let input = $(this).siblings('.qty-input');
            let current = parseInt(input.val());
            console.log(current);
            @* console.log(maxQty); *@

            if (current > 1) {
                input.val(current - 1);
                @* if (maxQty == 0) {
                    maxQty = current;
                } *@
            }
        });
    });
</script>

PizzaShop/Views/AccountManagerOrderApp/_MenuItemCard.cshtml
@model List<Entities.ViewModel.MenuCategoryVM>

<div class="d-flex flex-wrap ms-2">
    @foreach (var item in Model)
    {
        <div class="">
            <div class="card MenuItemCard mx-2 shadow mb-3" style="width: 18rem; border-radius: 0.5rem; overflow: hidden;" data-itemid="@item.ItemId" >
                <div class="d-flex flex-row flex-wrap ">
                    <div class="bg-light" style="width: 5rem;">
                        <img src="@(string.IsNullOrEmpty(item.ItemPhoto) ? Url.Content("~/assest/dining-menu.png") : @item.ItemPhoto)"
                            class="img-fluid p-2" style="width: 80px; height: 80px;" />
                    </div>
                    <div class="p-2 position-relative flex-grow-1 text-wrap">
                        @if (@item.ItemtypeId == 1)
                        {
                            <div class="bookmark" style=" border-top: 30px solid #00a651 !important;"></div>
                        }
                        else if (@item.ItemtypeId == 2)
                        {
                            <div class="bookmark" style=" border-top: 30px solid #f14338 !important;"></div>
                        }
                        else
                        {
                            <div class="bookmark" style=" border-top: 30px solid #ff9800 !important;"></div>
                        }

                        <h6 class="fw-bold fs-6 mb-3">@item.ItemName</h6>
                        <div class="d-flex justify-content-between align-items-center flex-wrap"  >
                            <p class="text-muted mb-1">₹@item.Rate</p>
                            @if (item.IsFavourite == true)
                            {
                                <i class="bi bi-heart-fill favoritebtn" style="color: rgba(0, 102, 167, 1);" data-itemid="@item.ItemId"></i>
                            }
                            else
                            {
                                <i class="bi bi-heart favoritebtn" data-itemid="@item.ItemId"></i>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

PizzaShop/Views/AccountManagerOrderApp/_MenuModifierPV.cshtml
@model Entities.ViewModel.MenuCategoryVM

<div class="d-flex justify-content-between align-items-center p-3">
    <div class="modal-title fw-bold fs-4 text-md">@Model.ItemName</div>
    <button class="close fs-2" data-bs-dismiss="modal">&times;</button>
</div>


@foreach (var modifiergrp in Model.ModifierGroupIds)
{
    <div class="d-flex flex-col justify-space-between ms-3">
        <div class="d-flex align-items-center text-secondary gap-2">
            <span class="fw-bold fs-5 ">@modifiergrp.ModifierGroupName </span>
            <span>(You can choose Minimum - @modifiergrp.MinSelection & Maximum - @modifiergrp.MaxSelection options)</span>
        </div>
    </div>
    <div class="d-flex flex-row mt-3 ms-2">
        @foreach (var modifier in modifiergrp.MenuModifiers)
        {

            <div class="card ModifierCard mx-2 mb-3" style="width: 10rem; border-radius: 0.5rem; overflow: hidden;" data-modid="@modifier.ModifierId" data-id="@Model.ItemId">

                <div class="p-2 position-relative flex-grow-1 text-wrap">
                    <div class="bookmark" style=" border-top: 15px solid #ff9800 !important;border-left: 15px solid transparent !important;"></div>


                    <h6 class="fw-normal fs-6">@modifier.ModifierName</h6>
                    <p class="text-muted mb-1">₹@modifier.ModifierRate</p>
                </div>
            </div>
        }
    </div>
}


<div class="modal-footer">
    <button type="submit" class="btn finalsavebtn modifieraddbtn px-4">Add</button>
    <button type="button" class="btn finalcancelbtn px-4" data-bs-dismiss="modal">Close</button>
</div>